var Source = Parsect.Source;
var string = Parsect.string;
var regexp = Parsect.regexp;
var ret = Parsect.ret;
var seq = Parsect.seq;
var number = Parsect.number;
var many = Parsect.many;
var many1 = Parsect.many1;
var option = Parsect.option;
var count = Parsect.count;
var map = Parsect.map;
var series = Parsect.series;
var or = Parsect.or;
//@ sourceMappingURL=globals.js.map
